In [3]:
import tensorflow as tf
import os
import keras
import numpy as np
import easygdf
import mne
import json
import pandas as pd


Save data from gdf file to csv

In [ ]:

filenames = ["A01T.gdf", "A01E.gdf", "A02T.gdf", "A02E.gdf","A03T.gdf","A03E.gdf","A04T.gdf","A04E.gdf","A05T.gdf","A05E.gdf","A06T.gdf","A06E.gdf","A07T.gdf","A07E.gdf","A08T.gdf","A08E.gdf","A09T.gdf","A09E.gdf"]
labels = ["A01T", "A01E", "A02T", "A02E","A03T","A03E","A04T","A04E","A05T","A05E","A06T","A06E","A07T","A07E","A08T","A08E","A09T","A09E"]

# Iterate over the filenames and labels
for filename, label in zip(filenames, labels):
    # Read the raw data
    filename='../datasets/BCICIV_2a_gdf/'+filename
    raw = mne.io.read_raw_gdf(filename)
    
    # Convert to DataFrame
    df = raw.to_data_frame()
    
    # Save to CSV
    df.to_csv('excel/'+label + '.csv', index=False)


seprate events from gdf files


In [34]:
filename = '../datasets/BCICIV_2a_gdf/A01T.gdf'
raw = mne.io.read_raw_gdf(filename)

# Access event information from the raw object
events, event_id = mne.events_from_annotations(raw)

#the list have the dictionary that map each events' id  to events' labels
events_id_labels = list(event_id.keys())

#create array for gather togther events' type and positions
events_with_labels= np.zeros_like(events)



for i in range(len(events)):
    events_with_labels[i,0]=events[i,0]
    id=events[i,2]
    events_with_labels[i,1]=events_id_labels[id-1] # be in dalil ke dar list event ha ma id 10 drim vali araye events_id_labels k az tarigh key dastresi peyda krdim yedone adadash paiin tare
        
print("nima")



Extracting EDF parameters from d:\porojects\EEG classification\datasets\BCICIV_2a_gdf\A01T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG, EOG-left, EOG-central, EOG-right
Creating raw.info structure...
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
nima


C:\Users\nima8\AppData\Local\Programs\Python\Python38\lib\contextlib.py:120: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


In [17]:


# Get the sample indices of the events
event_positions_samples = events[:, 0]

# Get the corresponding time points from raw
event_positions_times = raw.times[event_positions_samples]

# Print event positions (times)
print("Event Positions (Times):", event_positions_times)

Event Positions (Times): [   0.       0.     126.052  126.052  230.408  230.408  384.636  386.036
  388.036  394.048  396.048  401.72   403.72   409.528  411.528  417.56
  419.56   426.004  428.004  433.672  435.672  441.872  443.872  449.596
  451.596  457.588  459.588  465.212  467.212  472.792  474.792  480.68
  482.68   488.456  490.456  496.324  498.324  504.804  506.804  512.836
  514.836  521.1    523.1    529.244  531.244  537.508  539.508  545.788
  547.788  554.108  556.108  561.756  563.756  569.88   571.88   577.692
  579.692  585.536  587.536  593.952  595.952  601.968  603.968  609.868
  611.868  617.972  619.972  626.256  628.256  634.684  636.684  643.052
  645.052  651.416  653.416  659.588  661.588  667.844  669.844  675.924
  677.924  683.812  685.812  691.664  693.664  699.364  701.364  707.688
  709.688  715.6    717.6    723.56   725.56   732.036  734.036  739.66
  741.66   747.372  749.372  755.828  757.828  764.064  766.064  771.976
  773.376  775.376  781.388  

In [7]:
# Create a DataFrame from the event information
event_df = pd.DataFrame({
    'Event Type': events[:, 2],  # Event types
    'Event Position': events[:, 0],  # Event positions (samples)
    'Event du': events[:, 1]  # Event positions (samples)
})

# Save DataFrame to Excel file
excel_filename = 'event_info.xlsx'
event_df.to_excel(excel_filename, index=False)

print("Event information saved to", excel_filename)

Event information saved to event_info.xlsx


see all information in files

In [6]:
filename = '../datasets/BCICIV_2a_gdf/A02T.gdf'
raw = mne.io.read_raw_gdf(filename)

# Print basic information about the dataset
print(raw.info)

# Print channel names
print(raw.ch_names)

# Print data shape
print(raw.get_data().shape)

# Print sampling frequency
print(raw.info['sfreq'])

# Print events
events, event_id = mne.events_from_annotations(raw)
print(events)

# Print event IDs
print(event_id)

Extracting EDF parameters from d:\porojects\EEG classification\datasets\BCICIV_2a_gdf\A02T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG, EOG-left, EOG-central, EOG-right
Creating raw.info structure...
<Info | 8 non-empty values
 bads: []
 ch_names: EEG-Fz, EEG-0, EEG-1, EEG-2, EEG-3, EEG-4, EEG-5, EEG-C3, EEG-6, ...
 chs: 25 EEG
 custom_ref_applied: False
 highpass: 0.5 Hz
 lowpass: 100.0 Hz
 meas_date: 2004-11-15 12:00:00 UTC
 nchan: 25
 projs: []
 sfreq: 250.0 Hz
 subject_info: 4 items (dict)
>
['EEG-Fz', 'EEG-0', 'EEG-1', 'EEG-2', 'EEG-3', 'EEG-4', 'EEG-5', 'EEG-C3', 'EEG-6', 'EEG-Cz', 'EEG-7', 'EEG-C4', 'EEG-8', 'EEG-9', 'EEG-10', 'EEG-11', 'EEG-12', 'EEG-13', 'EEG-14', 'EEG-Pz', 'EEG-15', 'EEG-16', 'EOG-left', 'EOG-central', 'EOG-right']


C:\Users\nima8\AppData\Local\Programs\Python\Python38\lib\contextlib.py:120: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


(25, 677169)
250.0
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
[[     0      0      5]
 [     0      0      3]
 [ 31513      0      5]
 ...
 [673632      0      7]
 [675191      0      6]
 [675691      0      9]]
{'1023': 1, '1072': 2, '276': 3, '277': 4, '32766': 5, '768': 6, '769': 7, '770': 8, '771': 9, '772': 10}
